INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('ARROZ', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('PROTEINA', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('CARBOIDRATO', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('pao', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('CARBOIDRATO', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('PROTEINA', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('CARBOIDRATO', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('CARBOIDRATO', 0);

INSERT INTO TIPO (TIPO_COMIDA,INATIVO)
VALUES('PROTEINA', 0);
