INSERT INTO COMIDAS ( COMIDA,INATIVO)
VALUES('FRANGO', 0);
INSERT INTO COMIDAS ( COMIDA,INATIVO)
VALUES('CARNE VERMELHA', 1);

INSERT INTO COMIDAS ( COMIDA,INATIVO)
VALUES('PEIXE', 0);

INSERT INTO COMIDAS ( COMIDA,INATIVO)
VALUES('CACADA', 1);

INSERT INTO COMIDAS ( COMIDA,INATIVO)
VALUES('PERU', 1);
