INSERT INTO CARDAPIO(CARDAPIO, INATIVO )
VALUES("PRATO DO DIA",0);

INSERT INTO CARDAPIO(CARDAPIO, INATIVO )
VALUES("FRITAS",0);

INSERT INTO CARDAPIO(CARDAPIO, INATIVO )
VALUES("BEBIDAS",0);

INSERT INTO CARDAPIO(CARDAPIO, INATIVO )
VALUES("ADICIONAIS",0);

INSERT INTO CARDAPIO(CARDAPIO, INATIVO )
VALUES("SEI LA",0);

INSERT INTO CARDAPIO(CARDAPIO, INATIVO )
VALUES("OI GALERINHA",0);
