INSERT INTO COMIDA_INGREDIENTES (ID , ID_COMIDA , ID_INGREDIENTES)
VALUES(1, 2 ,4);

INSERT INTO COMIDA_INGREDIENTES (ID , ID_COMIDA , ID_INGREDIENTES)
VALUES(2,  ,4);

INSERT INTO COMIDA_INGREDIENTES (ID , ID_COMIDA , ID_INGREDIENTES)
VALUES(1, 2 ,4);

INSERT INTO COMIDA_INGREDIENTES (ID , ID_COMIDA , ID_INGREDIENTES)
VALUES(1, 2 ,4);

INSERT INTO COMIDA_INGREDIENTES (ID , ID_COMIDA , ID_INGREDIENTES)
VALUES(1, 2 ,4);

INSERT INTO COMIDA_INGREDIENTES (ID , ID_COMIDA , ID_INGREDIENTES)
VALUES(1, 2 ,4);
