INSERT INTO COMIDA_TIPO (ID_COMIDA, ID_TIPO)
VALUES(3, 2);

INSERT INTO COMIDA_TIPO (ID_COMIDA, ID_TIPO)
VALUES(4, 2);

INSERT INTO COMIDA_TIPO (ID_COMIDA, ID_TIPO)
VALUES(5, 2);

INSERT INTO COMIDA_TIPO (ID_COMIDA, ID_TIPO)
VALUES(1, 1);

INSERT INTO COMIDA_TIPO (ID_COMIDA, ID_TIPO)
VALUES( 2, 5);
