INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES( 'OVO', 0);
INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('CHOCOLATE EM PÓ', 0);
INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES( 'MARGARINA', 1);
INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES( 'BOLACHA', 0);
INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES( 'LEITE', 1);
INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('FARINHA', 1);
INSERT INTO INGREDIENTES (INGREDIENTES,INATIVO)
VALUES('ÁGUA', 1);
