INSERT INTO COMIDA_TIPO (ID, ID_COMIDA, ID_TIPO)
VALUES(1, 3, 1);

INSERT INTO COMIDA_TIPO (ID, ID_COMIDA, ID_TIPO)
VALUES(2, 4, 2);

INSERT INTO COMIDA_TIPO (ID, ID_COMIDA, ID_TIPO)
VALUES(3, 5, 2);

INSERT INTO COMIDA_TIPO (ID, ID_COMIDA, ID_TIPO)
VALUES(4, 1, 1);

INSERT INTO COMIDA_TIPO (ID, ID_COMIDA, ID_TIPO)
VALUES(5, 2, 5);
