INSERT INTO TIPO (ID, TIPO_COMIDA,INATIVO)
VALUES(2, 'PROTEINA', 0);

INSERT INTO TIPO (ID, TIPO_COMIDA,INATIVO)
VALUES(3, 'CARBOIDRATO', 0);

INSERT INTO TIPO (ID, TIPO_COMIDA,INATIVO)
VALUES(4, 'pao', 0);

INSERT INTO TIPO (ID, TIPO_COMIDA,INATIVO)
VALUES(5, 'CARBOIDRATO', 0);

INSERT INTO TIPO (ID, TIPO_COMIDA,INATIVO)
VALUES(6, 'PROTEINA', 0);

INSERT INTO TIPO (ID, TIPO_COMIDA,INATIVO)
VALUES(7, 'CARBOIDRATO', 0);

INSERT INTO TIPO (ID, TIPO_COMIDA,INATIVO)
VALUES(8, 'CARBOIDRATO', 0);

INSERT INTO TIPO (ID, TIPO_COMIDA,INATIVO)
VALUES(9, 'PROTEINA', 0);
