INSERT INTO INGREDIENTES (ID, INGREDIENTES,INATIVO)
VALUES(1, 'OVO', 0);
INSERT INTO INGREDIENTES (ID, INGREDIENTES,INATIVO)
VALUES(2, 'CHOCOLATE EM PÓ', 0);
INSERT INTO INGREDIENTES (ID, INGREDIENTES,INATIVO)
VALUES(3, 'MARGARINA', 1);
INSERT INTO INGREDIENTES (ID, INGREDIENTES,INATIVO)
VALUES(4, 'BOLACHA', 0);
INSERT INTO INGREDIENTES (ID, INGREDIENTES,INATIVO)
VALUES(5, 'LEITE', 1);
INSERT INTO INGREDIENTES (ID, INGREDIENTES,INATIVO)
VALUES(6, 'FARINHA', 1);
INSERT INTO INGREDIENTES (ID, INGREDIENTES,INATIVO)
VALUES(7, 'ÁGUA', 1);
