INSERT INTO COMIDAS (ID, COMIDA,INATIVO)
VALUES(1, 'FRANGO', 0);
INSERT INTO COMIDAS (ID, COMIDA,INATIVO)
VALUES(2, 'CARNE VERMELHA', 1);

INSERT INTO COMIDAS (ID, COMIDA,INATIVO)
VALUES(3, 'PEIXE', 0);

INSERT INTO COMIDAS (ID, COMIDA,INATIVO)
VALUES(4, 'CACADA', 1);

INSERT INTO COMIDAS (ID, COMIDA,INATIVO)
VALUES(5, 'PERU', 1);
