INSERT INTO TAMANHOS(PESO_MARMITA, INATIVO )
VALUES(12,0);

INSERT INTO TAMANHOS(PESO_MARMITA, INATIVO )
VALUES(14,0);

INSERT INTO TAMANHOS(PESO_MARMITA, INATIVO )
VALUES(15,0);

INSERT INTO TAMANHOS(PESO_MARMITA, INATIVO )
VALUES(11,1);

INSERT INTO TAMANHOS(PESO_MARMITA, INATIVO )
VALUES(5,1);


INSERT INTO TAMANHOS(PESO_MARMITA, INATIVO )
VALUES(18,1);

INSERT INTO TAMANHOS(PESO_MARMITA, INATIVO )
VALUES(19,0);
