INSERT INTO CARDAPIO_COMIDA(ID_COMIDA, ID_CARDAPIO )
VALUES(1,1);

INSERT INTO CARDAPIO_COMIDA(ID_COMIDA, ID_CARDAPIO )
VALUES(2,2);

INSERT INTO CARDAPIO_COMIDA(ID_COMIDA, ID_CARDAPIO )
VALUES(3,3);

INSERT INTO CARDAPIO_COMIDA(ID_COMIDA, ID_CARDAPIO )
VALUES(4,4);
