CREATE TABLE COMIDA_TIPO(
ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_COMIDA INTEGER NOT NULL,
ID_TIPO INTEGER NOT NULL,
CONSTRAINT FK_COMIDA_TIPO_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPO (ID),
CONSTRAINT FK_COMIDA_TIPO_COMIDA FOREIGN KEY (ID_COMIDA) REFERENCES COMIDAS (ID)
);
