CREATE TABLE CLIENTES(
ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(11) NOT NULL UNIQUE KEY,
TELEFONE VARCHAR(11) NOT NULL,
SENHA VARCHAR(10) NOT NULL,
CEP VARCHAR(8) NOT NULL,
LOGRADOURO VARCHAR(100) NOT NULL,
NUMERO INTEGER NOT NULL,
BAIRRO VARCHAR(100) NOT NULL
);
