CREATE TABLE COMIDA_INGREDIENTES(
ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_COMIDA INTEGER NOT NULL,
ID_INGREDIENTES INTEGER NOT NULL,
CONSTRAINT FK_COMIDA_INGREDIENTES_INGREDIENTE FOREIGN KEY (ID_INGREDIENTES) REFERENCES INGREDIENTES (ID),
CONSTRAINT FK_COMIDA_INGREDIENTES_COMIDA FOREIGN KEY (ID_COMIDA) REFERENCES COMIDAS (ID)
);
