CREATE TABLE CARDAPIO_COMIDA(
ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_COMIDA INTEGER NOT NULL,
ID_CARDAPIO INTEGER NOT NULL,
CONSTRAINT FK_CARDAPIO_COMIDA_CARDAPIO FOREIGN KEY (ID_CARDAPIO) REFERENCES CARDAPIO (ID),
CONSTRAINT FK_CARDAPIO_COMIDA_COMIDA FOREIGN KEY (ID_COMIDA) REFERENCES COMIDAS (ID)
);
